// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package socialdb

import (
	"context"
)

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(SELECT 1 FROM follows WHERE follower_user_id = $1 AND followee_user_id = $2 AND status = 1)
`

type IsFollowingParams struct {
	FollowerUserID string `json:"follower_user_id"`
	FolloweeUserID string `json:"followee_user_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFollowing, arg.FollowerUserID, arg.FolloweeUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT follower_user_id, followee_user_id, status, created_at, updated_at FROM follows
WHERE followee_user_id = $1 AND status = 1
ORDER BY updated_at DESC, follower_user_id ASC LIMIT $2 OFFSET $3
`

type ListFollowersParams struct {
	FolloweeUserID string `json:"followee_user_id"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]Follow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers, arg.FolloweeUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Follow
	for rows.Next() {
		var i Follow
		if err := rows.Scan(
			&i.FollowerUserID,
			&i.FolloweeUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT follower_user_id, followee_user_id, status, created_at, updated_at FROM follows
WHERE follower_user_id = $1 AND status = 1
ORDER BY updated_at DESC, followee_user_id ASC LIMIT $2 OFFSET $3
`

type ListFollowingParams struct {
	FollowerUserID string `json:"follower_user_id"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]Follow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing, arg.FollowerUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Follow
	for rows.Next() {
		var i Follow
		if err := rows.Scan(
			&i.FollowerUserID,
			&i.FolloweeUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFollow = `-- name: SetFollow :one
INSERT INTO follows (follower_user_id, followee_user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (follower_user_id, followee_user_id) DO UPDATE SET
    status = EXCLUDED.status, updated_at = CURRENT_TIMESTAMP
RETURNING follower_user_id, followee_user_id, status, created_at, updated_at
`

type SetFollowParams struct {
	FollowerUserID string `json:"follower_user_id"`
	FolloweeUserID string `json:"followee_user_id"`
	Status         int16  `json:"status"`
}

func (q *Queries) SetFollow(ctx context.Context, arg SetFollowParams) (Follow, error) {
	row := q.db.QueryRowContext(ctx, setFollow, arg.FollowerUserID, arg.FolloweeUserID, arg.Status)
	var i Follow
	err := row.Scan(
		&i.FollowerUserID,
		&i.FolloweeUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE user_id = $1 AND status = 0)
`

func (q *Queries) UserExists(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
