// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package socialdb

import (
	"time"
)

type Follow struct {
	FollowerUserID string    `json:"follower_user_id"`
	FolloweeUserID string    `json:"followee_user_id"`
	Status         int16     `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type User struct {
	UserID string `json:"user_id"`
	Status int16  `json:"status"`
}
