syntax = "proto3";

package protobuf;

option go_package = "./api/protobuf/user;user";

message ReqUserRegister {
    string user_name = 1; // 用户名
    string password = 2; // 密码
}

message ResUserRegister {
    int32 error_code = 1;
    string error_msg = 2;
    string user_id = 3; // 用户ID
}

message ReqUserLogin {
    string user_name = 1; // 用户名
    string password = 2; // 密码
}

message ResUserLogin {
    int32 error_code = 1;
    string error_msg = 2;
    string user_id = 3; // 用户ID
    string access_token = 4; // JWT访问令牌
    int64 expires_at = 5; // 令牌过期时间，Unix秒
}
