// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package contentdb

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Content struct {
	ContentID    string          `json:"content_id"`
	AuthorUserID string          `json:"author_user_id"`
	Text         string          `json:"text"`
	MediaUrls    json.RawMessage `json:"media_urls"`
	Status       int16           `json:"status"`
	LikeCount    int64           `json:"like_count"`
	CommentCount int64           `json:"comment_count"`
	CreatedAt    time.Time       `json:"created_at"`
	PublishedAt  sql.NullTime    `json:"published_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type ContentComment struct {
	CommentID    string    `json:"comment_id"`
	ContentID    string    `json:"content_id"`
	AuthorUserID string    `json:"author_user_id"`
	ParentID     string    `json:"parent_id"`
	Text         string    `json:"text"`
	Status       int16     `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type ContentLike struct {
	ContentID string    `json:"content_id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}
