// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package contentdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const addLike = `-- name: AddLike :exec
INSERT INTO content_likes (content_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddLikeParams struct {
	ContentID string `json:"content_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) AddLike(ctx context.Context, arg AddLikeParams) error {
	_, err := q.db.ExecContext(ctx, addLike, arg.ContentID, arg.UserID)
	return err
}

const countLikes = `-- name: CountLikes :one
SELECT COUNT(*) FROM content_likes WHERE content_id = $1
`

func (q *Queries) CountLikes(ctx context.Context, contentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLikes, contentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :exec
INSERT INTO content_comments (comment_id, content_id, author_user_id, parent_id, text, status)
VALUES ($1, $2, $3, $4, $5, 1)
`

type CreateCommentParams struct {
	CommentID    string `json:"comment_id"`
	ContentID    string `json:"content_id"`
	AuthorUserID string `json:"author_user_id"`
	ParentID     string `json:"parent_id"`
	Text         string `json:"text"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.CommentID,
		arg.ContentID,
		arg.AuthorUserID,
		arg.ParentID,
		arg.Text,
	)
	return err
}

const createContent = `-- name: CreateContent :exec
INSERT INTO contents (content_id, author_user_id, text, media_urls, status, like_count, comment_count, created_at, published_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 0, 0, $6, $7, $8)
`

type CreateContentParams struct {
	ContentID    string          `json:"content_id"`
	AuthorUserID string          `json:"author_user_id"`
	Text         string          `json:"text"`
	MediaUrls    json.RawMessage `json:"media_urls"`
	Status       int16           `json:"status"`
	CreatedAt    time.Time       `json:"created_at"`
	PublishedAt  sql.NullTime    `json:"published_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) error {
	_, err := q.db.ExecContext(ctx, createContent,
		arg.ContentID,
		arg.AuthorUserID,
		arg.Text,
		arg.MediaUrls,
		arg.Status,
		arg.CreatedAt,
		arg.PublishedAt,
		arg.UpdatedAt,
	)
	return err
}

const decrementCommentCount = `-- name: DecrementCommentCount :exec
UPDATE contents SET comment_count = GREATEST(comment_count - 1, 0), updated_at = $1
WHERE content_id = (SELECT content_id FROM content_comments WHERE comment_id = $2)
`

type DecrementCommentCountParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	CommentID string    `json:"comment_id"`
}

func (q *Queries) DecrementCommentCount(ctx context.Context, arg DecrementCommentCountParams) error {
	_, err := q.db.ExecContext(ctx, decrementCommentCount, arg.UpdatedAt, arg.CommentID)
	return err
}

const deleteComment = `-- name: DeleteComment :execrows
UPDATE content_comments SET status = 2 WHERE comment_id = $1 AND author_user_id = $2 AND status = 1
`

type DeleteCommentParams struct {
	CommentID    string `json:"comment_id"`
	AuthorUserID string `json:"author_user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteComment, arg.CommentID, arg.AuthorUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteContent = `-- name: DeleteContent :execrows
UPDATE contents SET status = 3, updated_at = $1 WHERE content_id = $2 AND status <> 3
`

type DeleteContentParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ContentID string    `json:"content_id"`
}

func (q *Queries) DeleteContent(ctx context.Context, arg DeleteContentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContent, arg.UpdatedAt, arg.ContentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getContent = `-- name: GetContent :one
SELECT content_id, author_user_id, text, media_urls, status, like_count, comment_count, created_at, published_at, updated_at
FROM contents WHERE content_id = $1
`

func (q *Queries) GetContent(ctx context.Context, contentID string) (Content, error) {
	row := q.db.QueryRowContext(ctx, getContent, contentID)
	var i Content
	err := row.Scan(
		&i.ContentID,
		&i.AuthorUserID,
		&i.Text,
		&i.MediaUrls,
		&i.Status,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCommentCount = `-- name: IncrementCommentCount :exec
UPDATE contents SET comment_count = comment_count + 1, updated_at = $1 WHERE content_id = $2
`

type IncrementCommentCountParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ContentID string    `json:"content_id"`
}

func (q *Queries) IncrementCommentCount(ctx context.Context, arg IncrementCommentCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementCommentCount, arg.UpdatedAt, arg.ContentID)
	return err
}

const listComments = `-- name: ListComments :many
SELECT comment_id, content_id, author_user_id, parent_id, text, status, created_at
FROM content_comments WHERE content_id = $1 AND status = 1 ORDER BY created_at ASC LIMIT $2 OFFSET $3
`

type ListCommentsParams struct {
	ContentID string `json:"content_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ContentComment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, arg.ContentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentComment
	for rows.Next() {
		var i ContentComment
		if err := rows.Scan(
			&i.CommentID,
			&i.ContentID,
			&i.AuthorUserID,
			&i.ParentID,
			&i.Text,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContents = `-- name: ListContents :many
SELECT content_id, author_user_id, text, media_urls, status, like_count, comment_count, created_at, published_at, updated_at
FROM contents WHERE author_user_id = $1 AND status <> 3 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListContentsParams struct {
	AuthorUserID string `json:"author_user_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListContents(ctx context.Context, arg ListContentsParams) ([]Content, error) {
	rows, err := q.db.QueryContext(ctx, listContents, arg.AuthorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ContentID,
			&i.AuthorUserID,
			&i.Text,
			&i.MediaUrls,
			&i.Status,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishContent = `-- name: PublishContent :execrows
UPDATE contents SET status = 2, published_at = $1, updated_at = $1 WHERE content_id = $2 AND status = 1
`

type PublishContentParams struct {
	PublishedAt sql.NullTime `json:"published_at"`
	ContentID   string       `json:"content_id"`
}

func (q *Queries) PublishContent(ctx context.Context, arg PublishContentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, publishContent, arg.PublishedAt, arg.ContentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeLike = `-- name: RemoveLike :exec
DELETE FROM content_likes WHERE content_id = $1 AND user_id = $2
`

type RemoveLikeParams struct {
	ContentID string `json:"content_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) RemoveLike(ctx context.Context, arg RemoveLikeParams) error {
	_, err := q.db.ExecContext(ctx, removeLike, arg.ContentID, arg.UserID)
	return err
}

const updateLikeCount = `-- name: UpdateLikeCount :exec
UPDATE contents SET like_count = $1, updated_at = $2 WHERE content_id = $3
`

type UpdateLikeCountParams struct {
	LikeCount int64     `json:"like_count"`
	UpdatedAt time.Time `json:"updated_at"`
	ContentID string    `json:"content_id"`
}

func (q *Queries) UpdateLikeCount(ctx context.Context, arg UpdateLikeCountParams) error {
	_, err := q.db.ExecContext(ctx, updateLikeCount, arg.LikeCount, arg.UpdatedAt, arg.ContentID)
	return err
}
