// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package messagedb

import (
	"database/sql"
	"time"
)

type Conversation struct {
	ConversationID   string         `json:"conversation_id"`
	ConversationType int16          `json:"conversation_type"`
	DirectKey        sql.NullString `json:"direct_key"`
	NextSeq          int64          `json:"next_seq"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type ConversationMember struct {
	ConversationID string    `json:"conversation_id"`
	UserID         string    `json:"user_id"`
	JoinedAt       time.Time `json:"joined_at"`
}

type Message struct {
	MessageID      string    `json:"message_id"`
	RequestID      string    `json:"request_id"`
	ConversationID string    `json:"conversation_id"`
	SenderUserID   string    `json:"sender_user_id"`
	TargetUserID   string    `json:"target_user_id"`
	MessageType    int16     `json:"message_type"`
	Content        string    `json:"content"`
	SentAt         int64     `json:"sent_at"`
	Seq            int64     `json:"seq"`
	CreatedAt      time.Time `json:"created_at"`
}
