// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package messagedb

import (
	"context"
	"database/sql"
)

const addConversationMembers = `-- name: AddConversationMembers :exec
INSERT INTO conversation_members (conversation_id, user_id)
VALUES ($1, $2), ($1, $3) ON CONFLICT DO NOTHING
`

type AddConversationMembersParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
	UserID_2       string `json:"user_id_2"`
}

func (q *Queries) AddConversationMembers(ctx context.Context, arg AddConversationMembersParams) error {
	_, err := q.db.ExecContext(ctx, addConversationMembers, arg.ConversationID, arg.UserID, arg.UserID_2)
	return err
}

const allocateMessageSequence = `-- name: AllocateMessageSequence :one
UPDATE conversations SET next_seq = next_seq + 1, updated_at = CURRENT_TIMESTAMP
WHERE conversation_id = $1 RETURNING next_seq
`

func (q *Queries) AllocateMessageSequence(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocateMessageSequence, conversationID)
	var next_seq int64
	err := row.Scan(&next_seq)
	return next_seq, err
}

const deleteMessage = `-- name: DeleteMessage :execrows
DELETE FROM messages WHERE message_id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, messageID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMessage, messageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT message_id, request_id, conversation_id, sender_user_id, target_user_id,
    message_type, content, sent_at, seq
FROM messages WHERE message_id = $1
`

type GetMessageByIDRow struct {
	MessageID      string `json:"message_id"`
	RequestID      string `json:"request_id"`
	ConversationID string `json:"conversation_id"`
	SenderUserID   string `json:"sender_user_id"`
	TargetUserID   string `json:"target_user_id"`
	MessageType    int16  `json:"message_type"`
	Content        string `json:"content"`
	SentAt         int64  `json:"sent_at"`
	Seq            int64  `json:"seq"`
}

func (q *Queries) GetMessageByID(ctx context.Context, messageID string) (GetMessageByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, messageID)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.MessageID,
		&i.RequestID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.TargetUserID,
		&i.MessageType,
		&i.Content,
		&i.SentAt,
		&i.Seq,
	)
	return i, err
}

const getMessageByRequest = `-- name: GetMessageByRequest :one
SELECT message_id, request_id, conversation_id, sender_user_id, target_user_id,
    message_type, content, sent_at, seq
FROM messages WHERE sender_user_id = $1 AND request_id = $2
`

type GetMessageByRequestParams struct {
	SenderUserID string `json:"sender_user_id"`
	RequestID    string `json:"request_id"`
}

type GetMessageByRequestRow struct {
	MessageID      string `json:"message_id"`
	RequestID      string `json:"request_id"`
	ConversationID string `json:"conversation_id"`
	SenderUserID   string `json:"sender_user_id"`
	TargetUserID   string `json:"target_user_id"`
	MessageType    int16  `json:"message_type"`
	Content        string `json:"content"`
	SentAt         int64  `json:"sent_at"`
	Seq            int64  `json:"seq"`
}

func (q *Queries) GetMessageByRequest(ctx context.Context, arg GetMessageByRequestParams) (GetMessageByRequestRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByRequest, arg.SenderUserID, arg.RequestID)
	var i GetMessageByRequestRow
	err := row.Scan(
		&i.MessageID,
		&i.RequestID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.TargetUserID,
		&i.MessageType,
		&i.Content,
		&i.SentAt,
		&i.Seq,
	)
	return i, err
}

const getOrCreateConversation = `-- name: GetOrCreateConversation :one
INSERT INTO conversations (conversation_id, conversation_type, direct_key)
VALUES ($1, $2, $3)
ON CONFLICT (direct_key) DO UPDATE SET updated_at = conversations.updated_at
RETURNING conversation_id
`

type GetOrCreateConversationParams struct {
	ConversationID   string         `json:"conversation_id"`
	ConversationType int16          `json:"conversation_type"`
	DirectKey        sql.NullString `json:"direct_key"`
}

func (q *Queries) GetOrCreateConversation(ctx context.Context, arg GetOrCreateConversationParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateConversation, arg.ConversationID, arg.ConversationType, arg.DirectKey)
	var conversation_id string
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (message_id, request_id, conversation_id, sender_user_id, target_user_id,
    message_type, content, sent_at, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING message_id, request_id, conversation_id, sender_user_id, target_user_id,
    message_type, content, sent_at, seq
`

type InsertMessageParams struct {
	MessageID      string `json:"message_id"`
	RequestID      string `json:"request_id"`
	ConversationID string `json:"conversation_id"`
	SenderUserID   string `json:"sender_user_id"`
	TargetUserID   string `json:"target_user_id"`
	MessageType    int16  `json:"message_type"`
	Content        string `json:"content"`
	SentAt         int64  `json:"sent_at"`
	Seq            int64  `json:"seq"`
}

type InsertMessageRow struct {
	MessageID      string `json:"message_id"`
	RequestID      string `json:"request_id"`
	ConversationID string `json:"conversation_id"`
	SenderUserID   string `json:"sender_user_id"`
	TargetUserID   string `json:"target_user_id"`
	MessageType    int16  `json:"message_type"`
	Content        string `json:"content"`
	SentAt         int64  `json:"sent_at"`
	Seq            int64  `json:"seq"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (InsertMessageRow, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.MessageID,
		arg.RequestID,
		arg.ConversationID,
		arg.SenderUserID,
		arg.TargetUserID,
		arg.MessageType,
		arg.Content,
		arg.SentAt,
		arg.Seq,
	)
	var i InsertMessageRow
	err := row.Scan(
		&i.MessageID,
		&i.RequestID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.TargetUserID,
		&i.MessageType,
		&i.Content,
		&i.SentAt,
		&i.Seq,
	)
	return i, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS (
    SELECT 1
    FROM conversation_members
    WHERE conversation_id = $1 AND user_id = $2
)
`

type IsConversationMemberParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT m.message_id, m.request_id, m.conversation_id, m.sender_user_id, m.target_user_id,
    m.message_type, m.content, m.sent_at, m.seq
FROM messages AS m
JOIN conversation_members AS member ON member.conversation_id = m.conversation_id
WHERE m.conversation_id = $1 AND member.user_id = $2 AND m.seq > $3
ORDER BY m.seq ASC
LIMIT $4
`

type ListConversationMessagesParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
	Seq            int64  `json:"seq"`
	Limit          int32  `json:"limit"`
}

type ListConversationMessagesRow struct {
	MessageID      string `json:"message_id"`
	RequestID      string `json:"request_id"`
	ConversationID string `json:"conversation_id"`
	SenderUserID   string `json:"sender_user_id"`
	TargetUserID   string `json:"target_user_id"`
	MessageType    int16  `json:"message_type"`
	Content        string `json:"content"`
	SentAt         int64  `json:"sent_at"`
	Seq            int64  `json:"seq"`
}

func (q *Queries) ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]ListConversationMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationMessages,
		arg.ConversationID,
		arg.UserID,
		arg.Seq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationMessagesRow
	for rows.Next() {
		var i ListConversationMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.RequestID,
			&i.ConversationID,
			&i.SenderUserID,
			&i.TargetUserID,
			&i.MessageType,
			&i.Content,
			&i.SentAt,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT c.conversation_id, peer.user_id AS peer_user_id, c.next_seq
FROM conversation_members AS member
JOIN conversations AS c ON c.conversation_id = member.conversation_id
JOIN conversation_members AS peer ON peer.conversation_id = c.conversation_id AND peer.user_id <> member.user_id
WHERE member.user_id = $1 AND c.conversation_type = 1 AND c.conversation_id > $2
ORDER BY c.conversation_id ASC
LIMIT $3
`

type ListUserConversationsParams struct {
	UserID         string `json:"user_id"`
	ConversationID string `json:"conversation_id"`
	Limit          int32  `json:"limit"`
}

type ListUserConversationsRow struct {
	ConversationID string `json:"conversation_id"`
	PeerUserID     string `json:"peer_user_id"`
	NextSeq        int64  `json:"next_seq"`
}

func (q *Queries) ListUserConversations(ctx context.Context, arg ListUserConversationsParams) ([]ListUserConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserConversations, arg.UserID, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserConversationsRow
	for rows.Next() {
		var i ListUserConversationsRow
		if err := rows.Scan(&i.ConversationID, &i.PeerUserID, &i.NextSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
