// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package userdb

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (user_id, user_name, password, phone, email, nickname, avatar, bio,
    gender, birthday, region, status, register_time, last_login_time, updated_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type CreateUserParams struct {
	UserID        string `json:"user_id"`
	UserName      string `json:"user_name"`
	Password      string `json:"password"`
	Phone         string `json:"phone"`
	Email         string `json:"email"`
	Nickname      string `json:"nickname"`
	Avatar        string `json:"avatar"`
	Bio           string `json:"bio"`
	Gender        int16  `json:"gender"`
	Birthday      int64  `json:"birthday"`
	Region        string `json:"region"`
	Status        int16  `json:"status"`
	RegisterTime  int64  `json:"register_time"`
	LastLoginTime int64  `json:"last_login_time"`
	UpdatedTime   int64  `json:"updated_time"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.UserID,
		arg.UserName,
		arg.Password,
		arg.Phone,
		arg.Email,
		arg.Nickname,
		arg.Avatar,
		arg.Bio,
		arg.Gender,
		arg.Birthday,
		arg.Region,
		arg.Status,
		arg.RegisterTime,
		arg.LastLoginTime,
		arg.UpdatedTime,
	)
	return err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT user_id, user_name, password, phone, email, nickname, avatar, bio,
    gender, birthday, region, status, register_time, last_login_time, updated_time
FROM users WHERE user_id = $1
`

func (q *Queries) GetUserByUserID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Password,
		&i.Phone,
		&i.Email,
		&i.Nickname,
		&i.Avatar,
		&i.Bio,
		&i.Gender,
		&i.Birthday,
		&i.Region,
		&i.Status,
		&i.RegisterTime,
		&i.LastLoginTime,
		&i.UpdatedTime,
	)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT user_id, user_name, password, phone, email, nickname, avatar, bio,
    gender, birthday, region, status, register_time, last_login_time, updated_time
FROM users WHERE LOWER(user_name) = LOWER($1)
`

func (q *Queries) GetUserByUserName(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserName, lower)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Password,
		&i.Phone,
		&i.Email,
		&i.Nickname,
		&i.Avatar,
		&i.Bio,
		&i.Gender,
		&i.Birthday,
		&i.Region,
		&i.Status,
		&i.RegisterTime,
		&i.LastLoginTime,
		&i.UpdatedTime,
	)
	return i, err
}

const updateLastLoginTime = `-- name: UpdateLastLoginTime :execrows
UPDATE users SET last_login_time = $1 WHERE user_id = $2
`

type UpdateLastLoginTimeParams struct {
	LastLoginTime int64  `json:"last_login_time"`
	UserID        string `json:"user_id"`
}

func (q *Queries) UpdateLastLoginTime(ctx context.Context, arg UpdateLastLoginTimeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLastLoginTime, arg.LastLoginTime, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const userNameExists = `-- name: UserNameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE LOWER(user_name) = LOWER($1))
`

func (q *Queries) UserNameExists(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userNameExists, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
