// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.2
// source: social/social.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowStatus int32

const (
	FollowStatus_FOLLOW_STATUS_UNSPECIFIED FollowStatus = 0 // 未指定关注状态
	FollowStatus_FOLLOW_STATUS_ACTIVE      FollowStatus = 1 // 有效关注状态
	FollowStatus_FOLLOW_STATUS_CANCELLED   FollowStatus = 2 // 已取消关注状态
)

// Enum value maps for FollowStatus.
var (
	FollowStatus_name = map[int32]string{
		0: "FOLLOW_STATUS_UNSPECIFIED",
		1: "FOLLOW_STATUS_ACTIVE",
		2: "FOLLOW_STATUS_CANCELLED",
	}
	FollowStatus_value = map[string]int32{
		"FOLLOW_STATUS_UNSPECIFIED": 0,
		"FOLLOW_STATUS_ACTIVE":      1,
		"FOLLOW_STATUS_CANCELLED":   2,
	}
)

func (x FollowStatus) Enum() *FollowStatus {
	p := new(FollowStatus)
	*p = x
	return p
}

func (x FollowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FollowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_social_social_proto_enumTypes[0].Descriptor()
}

func (FollowStatus) Type() protoreflect.EnumType {
	return &file_social_social_proto_enumTypes[0]
}

func (x FollowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FollowStatus.Descriptor instead.
func (FollowStatus) EnumDescriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{0}
}

type FollowRelation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowerUserId string       `protobuf:"bytes,1,opt,name=follower_user_id,json=followerUserId,proto3" json:"follower_user_id,omitempty"` // 关注发起用户ID
	FolloweeUserId string       `protobuf:"bytes,2,opt,name=followee_user_id,json=followeeUserId,proto3" json:"followee_user_id,omitempty"` // 被关注用户ID
	Status         FollowStatus `protobuf:"varint,3,opt,name=status,proto3,enum=protobuf.FollowStatus" json:"status,omitempty"`             // 关注关系状态
	CreatedAt      int64        `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                 // 首次关注时间，Unix秒
	UpdatedAt      int64        `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                 // 最后更新时间，Unix秒
}

func (x *FollowRelation) Reset() {
	*x = FollowRelation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRelation) ProtoMessage() {}

func (x *FollowRelation) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRelation.ProtoReflect.Descriptor instead.
func (*FollowRelation) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRelation) GetFollowerUserId() string {
	if x != nil {
		return x.FollowerUserId
	}
	return ""
}

func (x *FollowRelation) GetFolloweeUserId() string {
	if x != nil {
		return x.FolloweeUserId
	}
	return ""
}

func (x *FollowRelation) GetStatus() FollowStatus {
	if x != nil {
		return x.Status
	}
	return FollowStatus_FOLLOW_STATUS_UNSPECIFIED
}

func (x *FollowRelation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FollowRelation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CGSocialFollow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetUserId string `protobuf:"bytes,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // 被关注用户ID
}

func (x *CGSocialFollow) Reset() {
	*x = CGSocialFollow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGSocialFollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGSocialFollow) ProtoMessage() {}

func (x *CGSocialFollow) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGSocialFollow.ProtoReflect.Descriptor instead.
func (*CGSocialFollow) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{1}
}

func (x *CGSocialFollow) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type GCSocialFollow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32           `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 错误码，0表示成功
	ErrorMsg  string          `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`     // 错误信息
	Relation  *FollowRelation `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`                     // 当前关注关系
}

func (x *GCSocialFollow) Reset() {
	*x = GCSocialFollow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCSocialFollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSocialFollow) ProtoMessage() {}

func (x *GCSocialFollow) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSocialFollow.ProtoReflect.Descriptor instead.
func (*GCSocialFollow) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{2}
}

func (x *GCSocialFollow) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GCSocialFollow) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GCSocialFollow) GetRelation() *FollowRelation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type CGSocialUnfollow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetUserId string `protobuf:"bytes,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // 被取消关注用户ID
}

func (x *CGSocialUnfollow) Reset() {
	*x = CGSocialUnfollow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGSocialUnfollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGSocialUnfollow) ProtoMessage() {}

func (x *CGSocialUnfollow) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGSocialUnfollow.ProtoReflect.Descriptor instead.
func (*CGSocialUnfollow) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{3}
}

func (x *CGSocialUnfollow) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type GCSocialUnfollow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32           `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 错误码，0表示成功
	ErrorMsg  string          `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`     // 错误信息
	Relation  *FollowRelation `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`                     // 当前关注关系
}

func (x *GCSocialUnfollow) Reset() {
	*x = GCSocialUnfollow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCSocialUnfollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSocialUnfollow) ProtoMessage() {}

func (x *GCSocialUnfollow) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSocialUnfollow.ProtoReflect.Descriptor instead.
func (*GCSocialUnfollow) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{4}
}

func (x *GCSocialUnfollow) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GCSocialUnfollow) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GCSocialUnfollow) GetRelation() *FollowRelation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type CGSocialFollowingList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，从1开始
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
}

func (x *CGSocialFollowingList) Reset() {
	*x = CGSocialFollowingList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGSocialFollowingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGSocialFollowingList) ProtoMessage() {}

func (x *CGSocialFollowingList) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGSocialFollowingList.ProtoReflect.Descriptor instead.
func (*CGSocialFollowingList) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{5}
}

func (x *CGSocialFollowingList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CGSocialFollowingList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GCSocialFollowingList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32             `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 错误码，0表示成功
	ErrorMsg  string            `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`     // 错误信息
	Relations []*FollowRelation `protobuf:"bytes,3,rep,name=relations,proto3" json:"relations,omitempty"`                   // 当前用户的关注关系列表
}

func (x *GCSocialFollowingList) Reset() {
	*x = GCSocialFollowingList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCSocialFollowingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSocialFollowingList) ProtoMessage() {}

func (x *GCSocialFollowingList) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSocialFollowingList.ProtoReflect.Descriptor instead.
func (*GCSocialFollowingList) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{6}
}

func (x *GCSocialFollowingList) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GCSocialFollowingList) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GCSocialFollowingList) GetRelations() []*FollowRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type CGSocialFollowerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，从1开始
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
}

func (x *CGSocialFollowerList) Reset() {
	*x = CGSocialFollowerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGSocialFollowerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGSocialFollowerList) ProtoMessage() {}

func (x *CGSocialFollowerList) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGSocialFollowerList.ProtoReflect.Descriptor instead.
func (*CGSocialFollowerList) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{7}
}

func (x *CGSocialFollowerList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CGSocialFollowerList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GCSocialFollowerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32             `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 错误码，0表示成功
	ErrorMsg  string            `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`     // 错误信息
	Relations []*FollowRelation `protobuf:"bytes,3,rep,name=relations,proto3" json:"relations,omitempty"`                   // 当前用户的粉丝关系列表
}

func (x *GCSocialFollowerList) Reset() {
	*x = GCSocialFollowerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCSocialFollowerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSocialFollowerList) ProtoMessage() {}

func (x *GCSocialFollowerList) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSocialFollowerList.ProtoReflect.Descriptor instead.
func (*GCSocialFollowerList) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{8}
}

func (x *GCSocialFollowerList) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GCSocialFollowerList) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GCSocialFollowerList) GetRelations() []*FollowRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type CGSocialFollowCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetUserId string `protobuf:"bytes,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // 待检查的目标用户ID
}

func (x *CGSocialFollowCheck) Reset() {
	*x = CGSocialFollowCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGSocialFollowCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGSocialFollowCheck) ProtoMessage() {}

func (x *CGSocialFollowCheck) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGSocialFollowCheck.ProtoReflect.Descriptor instead.
func (*CGSocialFollowCheck) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{9}
}

func (x *CGSocialFollowCheck) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type GCSocialFollowCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 错误码，0表示成功
	ErrorMsg  string `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`     // 错误信息
	Following bool   `protobuf:"varint,3,opt,name=following,proto3" json:"following,omitempty"`                  // 当前用户是否关注目标用户
}

func (x *GCSocialFollowCheck) Reset() {
	*x = GCSocialFollowCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_social_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCSocialFollowCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSocialFollowCheck) ProtoMessage() {}

func (x *GCSocialFollowCheck) ProtoReflect() protoreflect.Message {
	mi := &file_social_social_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSocialFollowCheck.ProtoReflect.Descriptor instead.
func (*GCSocialFollowCheck) Descriptor() ([]byte, []int) {
	return file_social_social_proto_rawDescGZIP(), []int{10}
}

func (x *GCSocialFollowCheck) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GCSocialFollowCheck) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GCSocialFollowCheck) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

var File_social_social_proto protoreflect.FileDescriptor

var file_social_social_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22,
	0xd2, 0x01, 0x0a, 0x0e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x36, 0x0a, 0x0e, 0x43, 0x47, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x82, 0x01, 0x0a,
	0x0e, 0x47, 0x43, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x34, 0x0a, 0x08, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x38, 0x0a, 0x10, 0x43, 0x47, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x55, 0x6e, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x84, 0x01, 0x0a, 0x10,
	0x47, 0x43, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x55, 0x6e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x34, 0x0a, 0x08,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x48, 0x0a, 0x15, 0x43, 0x47, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x8b, 0x01, 0x0a,
	0x15, 0x47, 0x43, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x12, 0x36, 0x0a, 0x09, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x47, 0x0a, 0x14, 0x43, 0x47,
	0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x14, 0x47, 0x43, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x36, 0x0a, 0x09, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x3b, 0x0a, 0x13, 0x43, 0x47, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x6f, 0x0a,
	0x13, 0x47, 0x43, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x2a, 0x64,
	0x0a, 0x0c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d,
	0x0a, 0x19, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a,
	0x14, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41,
	0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x46, 0x4f, 0x4c, 0x4c, 0x4f,
	0x57, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c,
	0x45, 0x44, 0x10, 0x02, 0x42, 0x1e, 0x5a, 0x1c, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x3b, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_social_social_proto_rawDescOnce sync.Once
	file_social_social_proto_rawDescData = file_social_social_proto_rawDesc
)

func file_social_social_proto_rawDescGZIP() []byte {
	file_social_social_proto_rawDescOnce.Do(func() {
		file_social_social_proto_rawDescData = protoimpl.X.CompressGZIP(file_social_social_proto_rawDescData)
	})
	return file_social_social_proto_rawDescData
}

var file_social_social_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_social_social_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_social_social_proto_goTypes = []interface{}{
	(FollowStatus)(0),             // 0: protobuf.FollowStatus
	(*FollowRelation)(nil),        // 1: protobuf.FollowRelation
	(*CGSocialFollow)(nil),        // 2: protobuf.CGSocialFollow
	(*GCSocialFollow)(nil),        // 3: protobuf.GCSocialFollow
	(*CGSocialUnfollow)(nil),      // 4: protobuf.CGSocialUnfollow
	(*GCSocialUnfollow)(nil),      // 5: protobuf.GCSocialUnfollow
	(*CGSocialFollowingList)(nil), // 6: protobuf.CGSocialFollowingList
	(*GCSocialFollowingList)(nil), // 7: protobuf.GCSocialFollowingList
	(*CGSocialFollowerList)(nil),  // 8: protobuf.CGSocialFollowerList
	(*GCSocialFollowerList)(nil),  // 9: protobuf.GCSocialFollowerList
	(*CGSocialFollowCheck)(nil),   // 10: protobuf.CGSocialFollowCheck
	(*GCSocialFollowCheck)(nil),   // 11: protobuf.GCSocialFollowCheck
}
var file_social_social_proto_depIdxs = []int32{
	0, // 0: protobuf.FollowRelation.status:type_name -> protobuf.FollowStatus
	1, // 1: protobuf.GCSocialFollow.relation:type_name -> protobuf.FollowRelation
	1, // 2: protobuf.GCSocialUnfollow.relation:type_name -> protobuf.FollowRelation
	1, // 3: protobuf.GCSocialFollowingList.relations:type_name -> protobuf.FollowRelation
	1, // 4: protobuf.GCSocialFollowerList.relations:type_name -> protobuf.FollowRelation
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_social_social_proto_init() }
func file_social_social_proto_init() {
	if File_social_social_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_social_social_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowRelation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_social_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGSocialFollow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_social_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCSocialFollow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_social_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGSocialUnfollow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_social_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCSocialUnfollow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_social_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGSocialFollowingList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_social_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCSocialFollowingList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_social_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGSocialFollowerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_social_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCSocialFollowerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_social_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGSocialFollowCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_social_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCSocialFollowCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_social_social_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_social_social_proto_goTypes,
		DependencyIndexes: file_social_social_proto_depIdxs,
		EnumInfos:         file_social_social_proto_enumTypes,
		MessageInfos:      file_social_social_proto_msgTypes,
	}.Build()
	File_social_social_proto = out.File
	file_social_social_proto_rawDesc = nil
	file_social_social_proto_goTypes = nil
	file_social_social_proto_depIdxs = nil
}
